version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: metro_app
    restart: always
    ports:
      - '4230:3000'

networks:
  personal-network:
    name: personal-network
    external: true
